apiVersion : apps/v1
kind: Deployment
metadata:
  name: node-azure 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-azure
  template:
    metadata:
      labels:
        app: node-azure 
    spec:
      containers:
        - name: node-azure 
          image: opensoacr.azurecr.io/openso/node
          ports:
          - containerPort: 8080