apiVersion: v1
kind: Service
metadata:
  labels:
    name: node-azure
  name: node-azure
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: node-azure
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-azure
spec:
  selector:
    matchLabels:
      app: node-azure
  replicas: 1
  template:
    metadata:
      labels:
        app: node-azure
    spec:
      containers:
      - name: node-azure
        image: harbor.tanzuworld.com/apps/node:latest
        ports:
        - containerPort: 8080
