apiVersion : apps/v1
kind: Deployment
metadata:
  name: pensnodehttp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pensnodehttp
  template:
    metadata:
      labels:
        app: pensnodehttp 
    spec:
      containers:
        - name: pensnodehttp 
          image: opensoacr.azurecr.io/pensnodehttp
          ports:
          - containerPort: 8080